### ISSUE TITLE
Create special start and end pieces and integrate into the track generator

### ISSUE THREAD

**Issue by Mysterise** [racerr-io/unity-core#103]
Right now our track generator doesn't distinguish which pieces to use for the start and end pieces. 

What this means is, while we have a playable track, our track doesn't have special pieces indicating the start and end of the track. 

What we should have is a start piece that is long enough to accomodate our target max player number, closed off in the ends so they cannot escape, and a visible "start line" marker. The end piece should also be closed off, and have a visible "finish line" marker.

Also, this fixes the issue where players can just cheat by leaving the track and going back to the end.

What will probably need to be done:

1. Create special start and end piece prefabs
2. Integrate these pieces with the track generator - need to force the generator to start on the start piece, and end with the end piece.

**Comment by RFSurdsman** [comment]
Actually we do distinguish the piece to use for the start in the track generator. For this case, we just have to make the prefab.
