### ISSUE TITLE
Vehicle Physics

### ISSUE THREAD

**Issue by RFSurdsman** [racerr-io/unity-core#107]
The current vehicle physics system is something we have made ourselves using Unity's Wheel Colliders and it is garbage. It is extremely difficult to tune components of the car without screwing something else up.
We've agreed to use Edy's Vehicle Physics to replace our solution. The end result is that we hope to get a driving experience which is easily able to be fine tuned so that different car classes and abilities can be incorporated into the game.

**Comment by RFSurdsman** [comment]
Once PR #111 is merged, @Mysterise can take the pleasure of fine tuning the car

**Comment by Mysterise** [comment]
Done, now need to make it feel good in #115 .
