### ISSUE TITLE
(Re)Implement Client Spectate Feature

### ISSUE THREAD

**Issue by Mysterise** [racerr-io/unity-core#113]
We didn't port the spectate feature when we moved to the state machine model in #96. 

We want to reimplement that feature within our state machine model.

Players should be directed to the Client Spectate state when they die, or join a race that is currently in progress. 

When spectating, they should retain the common Race UI elements, and have their camera target focused on any existing player in the race. If the player they're spectating dies, they should be automatically directed to another existing player instead.

We can introduce manual spectate camera control (swapping target players) in the future as a separate issue.

**Comment by RFSurdsman** [comment]
Each state has an associated view. You can copy pasta the race view and rename it into spectate (in the scene it is under UX > UI). The UI elements should be the same (including minimap) and in the same positions, except you should delete speed. You should also create a simple UI component prefab (see the others like Speed and Countdown Timer in the Assets > UX > UI folder) that just has some text something like "Spectating Q16Solver" to make it clear that this is the spectate view. Place it somewhere suitable (maybe centre bottom of screen?)

**Comment by Q16solver** [comment]
Copy pasta code from client race state.
Remove speed component.
Add UI component "Spectating <player>".
