### ISSUE TITLE
Ability - Laser

### ISSUE THREAD

**Issue by RFSurdsman** [racerr-io/unity-core#135]
Let's implement a laser that the user can charge up and fire from the front of their car with infinite distance (inspiration: https://www.youtube.com/watch?v=kB40CHI48EY). It should be pretty easy with Unity raycasting. 
We need to design a simple ability system which is open for extension. The best solution is that each ability is a script which can be dragged onto the car prefab. Hence we can easily drag and drop abilities from various car classes in the future. The user can then charge and fire the ability using the space bar (or some other key). You will also need to think about a way where opponent cars can take damage from damaging abilities (e.g. how will it know it was hit by the laser? Do we check the collision in CarManager or somewhere else?)

**Comment by Mysterise** [comment]
No laser.

Recall our discussions with the design choice for abilities - they should live within the realm of vehicles & racing.
