### ISSUE TITLE
HUD

### ISSUE THREAD

**Issue by RFSurdsman** [racerr-io/unity-core#26]
HUD elements should not be randomly placed on the screen. We do not want to be doing repetitive things like this for each HUD element (this is currently in CarController.cs)
```c#
FindObjectOfType<HUDRPM>().Car = this;
FindObjectOfType<HUDSpeed>().Car = this;
```
We need a system as follows
- Create an abstract class called HUDElementCommon. This should store common methods and properties relevant to each HUD Element, such as Car. Even if it is just only Car it is still better than having to assign the car for each element on the HUD.
- Each HUD element (e.g. HUDRPM, HUDSpeed) now inherits from the abstract class.

Then whenever the user's car is instantiated we can simply do FindObjectsOfType<HUDElementCommon>() for HUDElementCommon type and for each assign the Car. (this could be a static method in HUDElementCommon class that is called by the CarController).

This issue is a prerequisite for #8 and #9.

**Comment by Mysterise** [comment]
Achieved within #94
