### ISSUE TITLE
Generating various track section "styles"

### ISSUE THREAD

**Issue by Mysterise** [racerr-io/unity-core#39]
For our prototype we only generated the standard 1-width street roads. We'd like to make the track more interesting and transition into different track "styles" for **consecutive sections**. 

This is probably more difficult than it'd seem like, as we'd need to incorporate a random style-change (i.e. going from 1-width street roads to highway roads, to 2-width roads etc) and use the appropriate "transition" track piece (which will physically facilitate the transition between the road styles).

**Comment by RFSurdsman** [comment]
Already done
