### ISSUE TITLE
Gears System for Acceleration

### ISSUE THREAD

**Issue by Mysterise** [racerr-io/unity-core#80]
Right now acceleration is simple, and appears to resemble a linear function curve. Essentially, your car accelerates at the same speed when it is going 20kph compared to when it is going 100kph.

We want acceleration to be more like a logarithmic function curve, where at lower speeds acceleration is fast and responsive, whereas it'll be much slower to accelerate at higher speeds.

To do this, we'll need to achieve a gear system, where a car has multiple gears (5-8?). The earlier gears would allow for faster acceleration but low speed range, later gears much slower acceleration but at the same time has a higher speed range,

Compliments the braking system in #79.

**Comment by RFSurdsman** [comment]
Covered by #107
