### ISSUE TITLE
Disable all car controllers during intermission state, enable when entering race state

### ISSUE THREAD

**Issue by Mysterise** [racerr-io/unity-core#97]
We move the spawning of player cars on the track from the moment we entered the server race state, to the moment when we generate the very first track piece called in the intermission state, as part of the refactoring effort #24 to have the cars ready for camera assignment.

Now, as the cars (and by extension, the player car controllers) are spawned in intermission, the players can move as soon as their cars are spawned WHILE the track is still generating and the race haven't officially started.

We need to disable the player's ability to control the car until the race starts (i.e. server enters race state).

**Comment by RFSurdsman** [comment]
Add a flag to CarController (IsDisabled) that keeps track of whether the car is disabled (if a car is disabled, any input is ignored). By default, when a car is instantiated it is disabled. As soon as the server transitions to Race State, cycle through all the Players in the race and set this flag to false.
